name: atm0s-single-zone
services:
  console:
   image: ghcr.io/8xff/atm0s-media-server:master
   network_mode: "host"
   command: ["console"]
   labels:
    - "com.centurylinklabs.watchtower.enable=true"
   env_file:
    - ./env/console.env
    - ./env/shared.env
   healthcheck:
    test: curl --fail http://localhost:8080 || exit 1
    interval: 20s
    timeout: 1s
    retries: 5
  gateway:
   image: ghcr.io/8xff/atm0s-media-server:master
   network_mode: "host"
   command: ["gateway"]
   labels:
    - "com.centurylinklabs.watchtower.enable=true"
   env_file:
    - ./env/gateway.env
    - ./env/shared.env
   healthcheck:
    test: curl --fail http://localhost:3001/token/ui || exit 1
    interval: 20s
    timeout: 1s
    retries: 5
   depends_on:
     console:
      condition: service_healthy
  connector:
   image: ghcr.io/8xff/atm0s-media-server:master
   network_mode: "host"
   command: ["connector"]
   labels:
    - "com.centurylinklabs.watchtower.enable=true"
   env_file:
    - ./env/connector.env
    - ./env/shared.env
   depends_on:
     gateway:
      condition: service_healthy
  media:
   image: ghcr.io/8xff/atm0s-media-server:master
   network_mode: "host"
   command: ["media"]
   labels:
    - "com.centurylinklabs.watchtower.enable=true"
   env_file:
    - ./env/media.env
    - ./env/shared.env
   depends_on:
     gateway:
      condition: service_healthy
  watchtower:
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WATCHTOWER_LABEL_ENABLE=true
